import { Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import Header from '@/components/Header/Header'
const font = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="nav">
           <Header />
        </div>
        <div>{children}</div>
      </body>
    </html>
  )
}
